include test/xspace.fs
include test/gos-space.fs
include test/gos-handles.fs
include test/template.fs
include test/contents.fs
include test/view-blog.fs
include test/urldecode.fs
include test/kvparse.fs
include test/escaper.fs
include test/permuter.fs
include test/articles-db.fs
